### ISSUE TITLE
Linker error

### ISSUE THREAD

**Issue by vitasam** [spacerace/stm32f103-freertos-v9.0.0#1]
Hi,
I'm trying to build this project in Ubuntu, and got a linker error:
```
$:~/GITprojects/stm32f103-freertos-v9.0.0$ make
  CC src/system_stm32f10x.c
  CC src/stm32f10x_it.c
  CC src/newlib_stubs.c
  CC src/fw_lib/core_cm3.c
  CC src/fw_lib/stm32f10x_rcc.c
  CC src/fw_lib/stm32f10x_gpio.c
  CC src/fw_lib/stm32f10x_usart.c
  CC src/fw_lib/extra_added/stm32f10x_systick.c
  CC src/fw_lib/misc.c
  CC src/freertos/croutine.c
  CC src/freertos/event_groups.c
  CC src/freertos/heap_1.c
  CC src/freertos/list.c
  CC src/freertos/port.c
  CC src/freertos/queue.c
  CC src/freertos/tasks.c
  CC src/freertos/timers.c
  CC src/main.c
  CC src/usart.c
  CC src/startup.S
/usr/lib/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/bin/ld: section .init loaded at [00000000080012a4,00000000080012a7] overlaps section .data loaded at [00000000080012a4,00000000080012bb]
collect2: error: ld returned 1 exit status
Makefile:73: recipe for target 'output/main.elf' failed
make: *** [output/main.elf] Error 1

```

Where the problem is?

**Comment by suwenqiang** [comment]
> Hi,
> I'm trying to build this project in Ubuntu, and got a linker error:
> 
> ```
> $:~/GITprojects/stm32f103-freertos-v9.0.0$ make
>   CC src/system_stm32f10x.c
>   CC src/stm32f10x_it.c
>   CC src/newlib_stubs.c
>   CC src/fw_lib/core_cm3.c
>   CC src/fw_lib/stm32f10x_rcc.c
>   CC src/fw_lib/stm32f10x_gpio.c
>   CC src/fw_lib/stm32f10x_usart.c
>   CC src/fw_lib/extra_added/stm32f10x_systick.c
>   CC src/fw_lib/misc.c
>   CC src/freertos/croutine.c
>   CC src/freertos/event_groups.c
>   CC src/freertos/heap_1.c
>   CC src/freertos/list.c
>   CC src/freertos/port.c
>   CC src/freertos/queue.c
>   CC src/freertos/tasks.c
>   CC src/freertos/timers.c
>   CC src/main.c
>   CC src/usart.c
>   CC src/startup.S
> /usr/lib/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/bin/ld: section .init loaded at [00000000080012a4,00000000080012a7] overlaps section .data loaded at [00000000080012a4,00000000080012bb]
> collect2: error: ld returned 1 exit status
> Makefile:73: recipe for target 'output/main.elf' failed
> make: *** [output/main.elf] Error 1
> ```
> 
> Where the problem is?

![image](https://user-images.githubusercontent.com/12077769/80347685-33e45100-889f-11ea-9fde-b1bea25bad5c.png)
the ld error can be fixed by this
